sudo: required

language: java
jdk:
 - openjdk8
 
services:
  - docker
 
before_install:
  - chmod +x mvnw
  
script: ./mvnw clean install 

after_success:
  - docker build -t pointinsights/springboot-gtd-alpha:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pointinsights/springboot-gtd-alpha:latest
  

 

 
